//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.10 at 04:44:51 PM CDT 
//


package com.aa.ndchtml5.domain;

import javax.xml.bind.annotation.XmlRegistry;

import com.aa.ndchtml5.domain.Offers.Offer;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules;
import com.aa.ndchtml5.domain.Offers.Offer.ForPurchaseFeatures;
import com.aa.ndchtml5.domain.Offers.Offer.IncludedFeatures;
import com.aa.ndchtml5.domain.Offers.Offer.Price;
import com.aa.ndchtml5.domain.Offers.Offer.SegmentDetail;
import com.aa.ndchtml5.domain.Offers.Offer.SliceDetail;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.Endorsement;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FeeApplies;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.Penalty;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.TicketByDate;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo.FareBasisCode;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo.FareComponent;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo.RelatedSegment;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo.FareComponent.BaseFare;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint.CurrencyCode;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.FareInfo.RelatedSegment.SegmentIDRef;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.Penalty.Change;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.Penalty.Change.PenaltyAmount;
import com.aa.ndchtml5.domain.Offers.Offer.FareRules.Penalty.Change.Taxes;
import com.aa.ndchtml5.domain.Offers.Offer.Price.Taxes.Tax;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Offers }
     * 
     */
    public Offers createOffers() {
        return new Offers();
    }

    /**
     * Create an instance of {@link Offers.Offer }
     * 
     */
    public Offers.Offer createOffersOffer() {
        return new Offers.Offer();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules }
     * 
     */
    public Offers.Offer.FareRules createOffersOfferFareRules() {
        return new Offers.Offer.FareRules();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.Penalty }
     * 
     */
    public Offers.Offer.FareRules.Penalty createOffersOfferFareRulesPenalty() {
        return new Offers.Offer.FareRules.Penalty();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.Penalty.Change }
     * 
     */
    public Offers.Offer.FareRules.Penalty.Change createOffersOfferFareRulesPenaltyChange() {
        return new Offers.Offer.FareRules.Penalty.Change();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo }
     * 
     */
    public Offers.Offer.FareRules.FareInfo createOffersOfferFareRulesFareInfo() {
        return new Offers.Offer.FareRules.FareInfo();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareComponent }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareComponent createOffersOfferFareRulesFareInfoFareComponent() {
        return new Offers.Offer.FareRules.FareInfo.FareComponent();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareComponent.Taxes }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareComponent.Taxes createOffersOfferFareRulesFareInfoFareComponentTaxes() {
        return new Offers.Offer.FareRules.FareInfo.FareComponent.Taxes();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax createOffersOfferFareRulesFareInfoFareComponentTaxesTax() {
        return new Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint createOffersOfferFareRulesFareInfoFareComponentTaxesTaxCollectionPoint() {
        return new Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.RelatedSegment }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.RelatedSegment createOffersOfferFareRulesFareInfoRelatedSegment() {
        return new Offers.Offer.FareRules.FareInfo.RelatedSegment();
    }

    /**
     * Create an instance of {@link Offers.Offer.Price }
     * 
     */
    public Offers.Offer.Price createOffersOfferPrice() {
        return new Offers.Offer.Price();
    }

    /**
     * Create an instance of {@link Offers.Offer.Price.Taxes }
     * 
     */
    public Offers.Offer.Price.Taxes createOffersOfferPriceTaxes() {
        return new Offers.Offer.Price.Taxes();
    }

    /**
     * Create an instance of {@link Offers.Offer.Price.Taxes.Tax }
     * 
     */
    public Offers.Offer.Price.Taxes.Tax createOffersOfferPriceTaxesTax() {
        return new Offers.Offer.Price.Taxes.Tax();
    }

    /**
     * Create an instance of {@link Offers.Offer.Price.Taxes.Tax.CollectionPoint }
     * 
     */
    public Offers.Offer.Price.Taxes.Tax.CollectionPoint createOffersOfferPriceTaxesTaxCollectionPoint() {
        return new Offers.Offer.Price.Taxes.Tax.CollectionPoint();
    }

    /**
     * Create an instance of {@link Offers.Offer.SliceDetail }
     * 
     */
    public Offers.Offer.SliceDetail createOffersOfferSliceDetail() {
        return new Offers.Offer.SliceDetail();
    }

    /**
     * Create an instance of {@link Offers.Offer.SegmentDetail }
     * 
     */
    public Offers.Offer.SegmentDetail createOffersOfferSegmentDetail() {
        return new Offers.Offer.SegmentDetail();
    }

    /**
     * Create an instance of {@link Offers.Offer.IncludedFeatures }
     * 
     */
    public Offers.Offer.IncludedFeatures createOffersOfferIncludedFeatures() {
        return new Offers.Offer.IncludedFeatures();
    }

    /**
     * Create an instance of {@link Offers.Offer.ForPurchaseFeatures }
     * 
     */
    public Offers.Offer.ForPurchaseFeatures createOffersOfferForPurchaseFeatures() {
        return new Offers.Offer.ForPurchaseFeatures();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.TicketByDate }
     * 
     */
    public Offers.Offer.FareRules.TicketByDate createOffersOfferFareRulesTicketByDate() {
        return new Offers.Offer.FareRules.TicketByDate();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.Endorsement }
     * 
     */
    public Offers.Offer.FareRules.Endorsement createOffersOfferFareRulesEndorsement() {
        return new Offers.Offer.FareRules.Endorsement();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FeeApplies }
     * 
     */
    public Offers.Offer.FareRules.FeeApplies createOffersOfferFareRulesFeeApplies() {
        return new Offers.Offer.FareRules.FeeApplies();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.Penalty.CurrencyCode }
     * 
     */
    public Offers.Offer.FareRules.Penalty.CurrencyCode createOffersOfferFareRulesPenaltyCurrencyCode() {
        return new Offers.Offer.FareRules.Penalty.CurrencyCode();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.Penalty.Change.PenaltyAmount }
     * 
     */
    public Offers.Offer.FareRules.Penalty.Change.PenaltyAmount createOffersOfferFareRulesPenaltyChangePenaltyAmount() {
        return new Offers.Offer.FareRules.Penalty.Change.PenaltyAmount();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.Penalty.Change.Taxes }
     * 
     */
    public Offers.Offer.FareRules.Penalty.Change.Taxes createOffersOfferFareRulesPenaltyChangeTaxes() {
        return new Offers.Offer.FareRules.Penalty.Change.Taxes();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareBasisCode }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareBasisCode createOffersOfferFareRulesFareInfoFareBasisCode() {
        return new Offers.Offer.FareRules.FareInfo.FareBasisCode();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareComponent.CurrencyCode }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareComponent.CurrencyCode createOffersOfferFareRulesFareInfoFareComponentCurrencyCode() {
        return new Offers.Offer.FareRules.FareInfo.FareComponent.CurrencyCode();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareComponent.BaseFare }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareComponent.BaseFare createOffersOfferFareRulesFareInfoFareComponentBaseFare() {
        return new Offers.Offer.FareRules.FareInfo.FareComponent.BaseFare();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint.CurrencyCode }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint.CurrencyCode createOffersOfferFareRulesFareInfoFareComponentTaxesTaxCollectionPointCurrencyCode() {
        return new Offers.Offer.FareRules.FareInfo.FareComponent.Taxes.Tax.CollectionPoint.CurrencyCode();
    }

    /**
     * Create an instance of {@link Offers.Offer.FareRules.FareInfo.RelatedSegment.SegmentIDRef }
     * 
     */
    public Offers.Offer.FareRules.FareInfo.RelatedSegment.SegmentIDRef createOffersOfferFareRulesFareInfoRelatedSegmentSegmentIDRef() {
        return new Offers.Offer.FareRules.FareInfo.RelatedSegment.SegmentIDRef();
    }

    /**
     * Create an instance of {@link Offers.Offer.Price.BaseFare }
     * 
     */
    public Offers.Offer.Price.BaseFare createOffersOfferPriceBaseFare() {
        return new Offers.Offer.Price.BaseFare();
    }

    /**
     * Create an instance of {@link Offers.Offer.Price.Taxes.Tax.CurrencyCode }
     * 
     */
    public Offers.Offer.Price.Taxes.Tax.CurrencyCode createOffersOfferPriceTaxesTaxCurrencyCode() {
        return new Offers.Offer.Price.Taxes.Tax.CurrencyCode();
    }

    /**
     * Create an instance of {@link Offers.Offer.Price.Taxes.Tax.CollectionPoint.CurrencyCode }
     * 
     */
    public Offers.Offer.Price.Taxes.Tax.CollectionPoint.CurrencyCode createOffersOfferPriceTaxesTaxCollectionPointCurrencyCode() {
        return new Offers.Offer.Price.Taxes.Tax.CollectionPoint.CurrencyCode();
    }

}
